services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      APP_NAME: "BEBAS Scanner"
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: http://localhost:8080
      DB_CONNECTION: pgsql
      DB_HOST: 103.185.52.138
      DB_PORT: 1185
      DB_DATABASE: abstrak_algorithm
      DB_USERNAME: abstrak_algorithm
      DB_PASSWORD: "RT!gMOB107&006TnlfIntrj)x]83inXQ"
      SESSION_DRIVER: file
      CACHE_STORE: file
      QUEUE_CONNECTION: sync
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    restart: unless-stopped
